# create a tictactoe game
#the game is played by two players
#the game is played on a 3x3 grid
#the game is played by entering a number from 1 to 9
print("#################################################################")
print()
print("               Tik-Tak-Toe")
print()
print("#################################################################")
print()
print("1. Play")
print("2. Exit")
print()
print("Enter your choice : ", end="")
choice = int(input())
print()
if choice == 1:
    print("Enter your name : ", end="")
    name = input()
    print("Enter your opponent's name : ", end="")
    opponent = input()
    print("Enter your symbol : ", end="")
    symbol = input()
    print("Enter your opponent's symbol : ", end="")
    opponent_symbol = input()
    print("Enter your move : ", end="")
    move = int(input())
    print("Enter your opponent's move : ", end="")
    opponent_move = int(input())
    # print out the game board
    print("#################################################################")
    print()
    print("               Tik-Tak-Toe")
    print()
    print("#################################################################")
    print()
    print("Player 1 : ", name)
    print("Player 2 : ", opponent)
    print("Player 1's symbol : ", symbol)
    print("Player 2's symbol : ", opponent_symbol)
    print("Player 1's move : ", move)
    print("Player 2's move : ", opponent_move)
    print("#################################################################")
    print()
    print("               Tik-Tak-Toe")
    print()
    print("#################################################################")
    print()
    # print out the grid
    print("#################################################################")
    print()
    print("               Tik-Tak-Toe")
    print()
    print("#################################################################")
    print()
    print("|1|2|3|")
    print("|4|5|6|")
    print("|7|8|9|")
    print("#################################################################")
    print()
    print("               Tik-Tak-Toe")
    print()
    print("#################################################################")
    print()
    # print out the game board
    print("#################################################################")
    print()
    print("               Tik-Tak-Toe")
    print()
    print("#################################################################")
    print()
    print("Player 1 : ", name)
    print("Player 2 : ", opponent)
    print("Player 1's symbol : ", symbol)
    print("Player 2's symbol : ", opponent_symbol)
    print("Player 1's move : ", move)
    print("Player 2's move : ", opponent_move)
    print("#################################################################")
    print()
    print("               Tik-Tak-Toe")
    print()
    print("#################################################################")
    print()